-- Migration: allow Saturday (day_of_week = 6) in timetables and permit advisors to manage Saturday rows

-- 1) Replace restrictive day_of_week check (1..5) with 1..6 if present
-- Drop the known check constraint if it exists (common name generated by CREATE TABLE)
ALTER TABLE public.timetables DROP CONSTRAINT IF EXISTS timetables_day_of_week_check;
-- Also drop any legacy named constraint we might have attempted to create earlier
ALTER TABLE public.timetables DROP CONSTRAINT IF EXISTS chk_timetables_day_of_week;

-- Add a new check allowing Saturday (1..6). Use the conventional name timetables_day_of_week_check
DO $$
BEGIN
  BEGIN
    ALTER TABLE public.timetables ADD CONSTRAINT timetables_day_of_week_check CHECK (day_of_week BETWEEN 1 AND 6);
  EXCEPTION WHEN duplicate_object THEN
    -- already exists, do nothing
    RAISE NOTICE 'timetables_day_of_week_check already exists';
  END;
END$$;

-- 2) Create a Row-Level Security policy that allows advisors to INSERT/UPDATE/DELETE Saturday rows (day_of_week = 6)
DROP POLICY IF EXISTS "Advisors can manage saturday timetables" ON public.timetables;

CREATE POLICY "Advisors can manage saturday timetables"
  ON public.timetables FOR ALL
  TO authenticated
  USING (
    day_of_week = 6 AND
    EXISTS (
      SELECT 1 FROM public.staff st JOIN public.profiles p ON p.id = st.id
      WHERE st.id = auth.uid()
        AND st.staff_role = 'advisor'
        AND p.department = timetables.department
        AND st.year = timetables.year
        AND st.section = timetables.section
    )
  )
  WITH CHECK (
    day_of_week = 6 AND
    EXISTS (
      SELECT 1 FROM public.staff st JOIN public.profiles p ON p.id = st.id
      WHERE st.id = auth.uid()
        AND st.staff_role = 'advisor'
        AND p.department = timetables.department
        AND st.year = timetables.year
        AND st.section = timetables.section
    )
  );

-- Note: This migration assumes advisors are stored in the `staff` table (joined to `profiles` by id)
-- and that `profiles.department` holds the staff's department. Run this in Supabase SQL editor as an
-- authenticated SQL (with sufficient privileges) to apply the changes.
